### ISSUE TITLE
step-value not updating

### ISSUE THREAD

**Issue by beebase** [rzajac/angularjs-slider#115]
Is this related to the width of the screen?
Seems to work ok in a broader view.

![steps](https://cloud.githubusercontent.com/assets/446089/9627816/06a69af0-5167-11e5-8091-92955e62b5f9.gif)

**Comment by ValentinH** [comment]
Could you please provide a fiddle showing this issue? (Please fork this one: http://jsfiddle.net/pq7yr6d6/)

**Comment by beebase** [comment]
http://jsfiddle.net/maartenfb/6jr0eha4/

Only seems to happen when decreasing the page width to phone like size.

**Comment by ValentinH** [comment]
Indeed there is a bug. This is due to this line: https://github.com/rzajac/angularjs-slider/blob/master/rzslider.js#L655 . I already had problem due to it but I don't know what is its purpose... It might be here only for optimization purpose but in small screen cases, it leads to a bug. I think that removing this line fix your problem...

**Comment by beebase** [comment]
commenting out that line fixed it :-)
Thanks.

**Comment by ValentinH** [comment]
Also I noticed that when you clicked on a increase/decrease button, there is a delay to update the slider. This is due to the throttle value here: https://github.com/rzajac/angularjs-slider/blob/master/rzslider.js#L294 . Setting a lower value than 350 reduce this lag.
