### ISSUE TITLE
[FEATURE REQUEST] Enabled/disabled option for slider

### ISSUE THREAD

**Issue by soee** [rzajac/angularjs-slider#117]
Hi again, 

correct me if i'm wrong but there is no feaure that allows to make slider disabled/enabled based on some expression (like using some attribute: `disabled="ctrl.enableSlider == true"`)?

Working on my project now i would like to have an option to quickly disable/enable slider instance based on some expression and when disabling it also clear/null it's value.

**Comment by ValentinH** [comment]
Indeed there is not such a feature and I think it would be nice indeed.

Setting its value to null is not possible because you can't give null values to the slider. I think in most application, when an input is disabled, the value is present but the style shows that it is disabled and the value can't be edited.

So for the slider, once it is disabled, I think we should prevent any editing and setting a different style that make it obvious that it is disabled.

What do you think?

**Comment by soee** [comment]
@ValentinH I agree with the slider thing. When disabled it shouldn't be draggable and the slider control should be grayed out by default than.

**Comment by ValentinH** [comment]
OK, if you are motivated you can start a pull request. Otherwise, I will work on it next week when I will be  back from holidays ;)

**Comment by soee** [comment]
@ValentinH Pleas do tak eit. I have full hands of work atm. :|

**Comment by ValentinH** [comment]
Let's see next week if I get time and motivation ;)

**Comment by Pritoj** [comment]
Can't this attribute perform the same thing essentially?

rz-slider-present-only

**Comment by ValentinH** [comment]
Yes this enables to remove all events on the slider but it can't be changed at runtime. Moreover, the disable feature should provide a default style for the disabled state.

**Comment by ValentinH** [comment]
Tell me if this is OK for you. ;)

**Comment by ValentinH** [comment]
See the example on this page: http://rzajac.github.io/angularjs-slider/index.html

**Comment by soee** [comment]
@ValentinH Looks cool. Can you release it with v0.1.35 ?

**Comment by ValentinH** [comment]
Just did it ;)
