### ISSUE TITLE
slider uniform distribution

### ISSUE THREAD

**Issue by kukac7** [rzajac/angularjs-slider#122]
I would like to ask for help.
of 6 sliders, which should be distributed to 500 points.
how can this be done with the slider?

**Comment by ValentinH** [comment]
I don't understand what you mean... Can you show a mockup or something pls?

**Comment by kukac7** [comment]
@ValentinH there are six questions, one question is where you can get up to 100 points.
but up to a total of 500 points.
this should be 500 points on 6 slider to distribute.
so you can understand?

**Comment by ValentinH** [comment]
So each slider has a value between 0 and 100, and you want to ensure that the total never pass 500?
Then I would use rz-slider-on-change on each slider and write my own logic...

**Comment by kukac7** [comment]
@ValentinH and the value of each change on the fly?

**Comment by ValentinH** [comment]
Like this: http://jsfiddle.net/vqep92wo/ .
In this fiddle, the logic to limit the other value is very stupid but this is the idea.
When you update, a slider model from the code, there is a small delay which is due to the leading: false of this line: https://github.com/rzajac/angularjs-slider/blob/master/rzslider.js#L305 . I think that I will remove it one day...

**Comment by ValentinH** [comment]
Here is a better version using the code without the leading parameter from on other branch: http://jsfiddle.net/LvqtL8u8/ . You can use `rz-slider-on-end` instead of on-change if you want the slider to only be updated on slider release.

**Comment by kukac7** [comment]
@ValentinH I talked about this! very good! thanks for the help! :clap: :+1: :bow:
